### ISSUE TITLE
Is this gem deprecated?

### ISSUE THREAD

**Issue by andrer0cha** [dreikanter/callee#9]
Well, this is a fantastic library that brings a lot of value to a project, so first of all, congrats on that.

That said, I saw that it has been a while since we don't have any new PRs and was wondering if this amazing tool was deprecated.
I want to add it to my company's project but we are worried that the gem might not have been supported anymore. Can someone help me with that?

**Comment by dreikanter** [comment]
Hi! It is not deprecated :) I'm using it in some projects. It's been a while since the last release for the only reason I don't really need much to change. And there are no new PRs from other contributors.
